# Generated by Django 2.0 on 2019-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='img/profiles/default.png', upload_to='img/profiles'),
        ),
    ]
