# Generated by Django 2.2 on 2019-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190426_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privacy',
            field=models.IntegerField(choices=[(1, 'following'), (2, 'all'), (3, 'nobody')], default=1, max_length=1),
        ),
    ]
