# Generated by Django 2.2 on 2019-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privacy',
            field=models.IntegerField(choices=[(1, 'following'), (2, 'all'), (3, 'nobody')], default=1),
        ),
    ]
