# Generated by Django 2.2 on 2019-04-27 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190427_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('user_id_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_one_following', to=settings.AUTH_USER_MODEL)),
                ('user_id_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_two_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
