# Generated by Django 2.2 on 2019-05-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190427_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_id_one',
            new_name='user_one',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user_id_two',
            new_name='user_two',
        ),
    ]
