# Generated by Django 2.2 on 2019-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fandomfanfic',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
