# Generated by Django 2.2 on 2019-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190515_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
