# Generated by Django 2.2 on 2019-05-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_fanfic_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
