# Generated by Django 2.2 on 2019-05-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_reading_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': ()},
        ),
    ]
