# Generated by Django 2.2 on 2019-05-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20190518_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fandom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Fandom'),
        ),
    ]
