# Generated by Django 2.2 on 2019-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20190519_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name_surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('name_surname', 'fandom')},
        ),
    ]
