# Generated by Django 2.2 on 2019-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190519_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterfanfic',
            options={'verbose_name': 'Characters in Fanfics'},
        ),
    ]
