# Generated by Django 2.2 on 2019-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20190520_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterfanfic',
            options={'verbose_name': 'Characters in Fanfics', 'verbose_name_plural': 'Characters in Fanfics'},
        ),
    ]
