# Generated by Django 2.2 on 2019-05-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20190520_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fandom',
            unique_together={('name', 'type')},
        ),
    ]
