# Generated by Django 2.2 on 2019-05-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20190520_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fandom',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.Type'),
            preserve_default=False,
        ),
    ]
