# Generated by Django 2.2 on 2019-05-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190520_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Media types', 'verbose_name_plural': 'Media types'},
        ),
    ]
