# Generated by Django 2.2 on 2019-05-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_chapter_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
