# Generated by Django 2.2 on 2019-05-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20190527_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
