# Generated by Django 2.2 on 2019-05-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_fanfic_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanfic',
            old_name='date',
            new_name='date_added',
        ),
    ]
