# Generated by Django 2.2 on 2019-05-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20190527_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UserFanficError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[(0, 'metadata'), (1, 'chapters'), (2, 'other')], max_length=3)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Fanfic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.List')),
            ],
            options={
                'verbose_name': 'User submitted errors',
                'verbose_name_plural': 'User submitted errors',
            },
        ),
    ]
