# Generated by Django 2.2 on 2019-05-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20190527_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFanficError',
            new_name='SubmittedReport',
        ),
        migrations.AlterModelOptions(
            name='submittedreport',
            options={'verbose_name': 'Submitted reports', 'verbose_name_plural': 'Submitted reports'},
        ),
    ]
