# Generated by Django 2.2 on 2019-05-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20190527_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedreport',
            name='comment',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
