# Generated by Django 2.2 on 2019-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20190528_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedreport',
            name='comment',
            field=models.TextField(),
        ),
    ]
