# Generated by Django 2.2 on 2019-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20190528_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedreport',
            name='issue',
            field=models.CharField(choices=[('m', 'metadata'), ('c', 'chapters'), ('o', 'other')], max_length=2),
        ),
    ]
