# Generated by Django 2.2 on 2019-05-28 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20190528_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
