# Generated by Django 2.0 on 2019-03-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('verb', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=10)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('structure', models.CharField(blank=True, max_length=4, null=True)),
                ('read', models.BooleanField(default=False)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('only_in_feed', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
