# Generated by Django 2.0 on 2019-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20190329_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(max_length=60),
        ),
    ]
