# Generated by Django 2.0 on 2019-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_auto_20190329_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='structure',
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
