# Generated by Django 2.2 on 2019-04-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_remove_notification_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='only_in_feed',
            new_name='in_top_bar',
        ),
        migrations.AddField(
            model_name='notification',
            name='in_feed',
            field=models.BooleanField(default=False),
        ),
    ]
