# Generated by Django 2.2 on 2019-04-28 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifier', '0007_auto_20190427_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
